# Kafka Configuration
kafka.bootstrap.servers=b-1.flinkstagingkafkaclus.oj6v2z.c23.kafka.us-east-1.amazonaws.com:9098,b-2.flinkstagingkafkaclus.oj6v2z.c23.kafka.us-east-1.amazonaws.com:9098
kafka.topic=user_behavior_01
kafka.group.id=flink_consumer_group
kafka.security.protocol=SASL_SSL
kafka.sasl.mechanism=AWS_MSK_IAM
kafka.sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required;
kafka.sasl.client.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler

# S3 Configuration
#//                        "    'path'='file:///tmp/output/user_action/'," +
#// "    'path'='s3://flink-bucket/user_action/'," +
s3.output.path=s3://jiazhi110-flink-staging-bucket/user_action/
s3.checkpoint.path=s3://jiazhi110-flink-staging-bucket/checkpoints/

# Flink Configuration
flink.parallelism=1
flink.checkpoint.interval=60000
flink.checkpoint.mode=EXACTLY_ONCE