# consumer
name: Flink ETL CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'flink_jobs/**'
      - 'Dockerfile'
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to build from'
        required: true
        default: 'develop'
        type: choice
        options:
        - main
        - develop

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Run Flink Job Tests
        working-directory: ./flink_jobs
        run: mvn test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          BRANCH_NAME: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref_name }}
          ECR_REPOSITORY: 'ingestion_kafka_flink'
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          IMAGE_TAG="flink-${{ env.BRANCH_NAME }}
          ${SHORT_SHA}"
          
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:flink-latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:flink-latest

          # Update SSM Parameter
          IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY:flink-latest"
          echo "Updating Flink image URI in SSM to: $IMAGE_URI"
          aws ssm put-parameter \
            --name "/data-platform/dev/ingestion/flink_job_image_url" \
            --value "$IMAGE_URI" \
            --type "String" \
            --overwrite
