# CI/CD pipeline for Mock Data Simulator (Build & Push)

name: Data Simulator Build & Push

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'mock_data/**'
      - '.github/workflows/data-simulator-pipeline.yml'
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to check out'
        required: true
        default: 'develop'
        type: choice
        options:
        - main
        - develop

jobs:
  run-mock-data-producer:
    name: Run Mock Data Producer
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies & Run Tests
        run: |
          pip install -r requirements.txt
          python -m pytest mock_data/tests/

      - name: Login to Amazon ECR
        id: login-ecr-producer
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        id: build-image-producer
        env:
          ECR_REGISTRY: ${{ steps.login-ecr-producer.outputs.registry }}
          ECR_REPOSITORY: 'ingestion_kafka_flink'
          BRANCH_NAME: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref_name }}
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          IMAGE_TAG="mockdata-${{ env.BRANCH_NAME }}-${SHORT_SHA}"

          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f mock_data/Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:mockdata-latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:mockdata-latest

          # Update SSM Parameter
          IMAGE_URI="$ECR_REGISTRY/$ECR_REPOSITORY:mockdata-latest"
          echo "Updating Mockdata image URI to: $IMAGE_URI"
          aws ssm put-parameter \
            --name "/data-platform/dev/ingestion/mockdata_producer_image_url" \
            --value "$IMAGE_URI" \
            --type "String" \
            --overwrite